# Tables and figures for the Benford equifinality benchmark

require_output_packages <- function() {
  needed <- c("ggplot2", "dplyr", "tidyr", "knitr")
  missing <- needed[!vapply(needed, requireNamespace, logical(1), quietly = TRUE)]
  if (length(missing)) stop("Missing R packages: ", paste(missing, collapse = ", "), ". Install them before rendering the Quarto document.")
}

save_latex_table <- function(x, file, caption = NULL, label = NULL, digits = 3) {
  dir.create(dirname(file), recursive = TRUE, showWarnings = FALSE)
  label_clean <- if (is.null(label)) NULL else sub("^tab:", "", label)
  tex <- knitr::kable(x, format="latex", booktabs=TRUE, escape=FALSE, digits=digits, caption=caption, label=label_clean)
  writeLines(tex, con=file); invisible(tex)
}

make_design_table <- function(n_seq, seq_len, rho, theta) data.frame(
  Construction=c("iid Benford reference","Stochastic multiplicative","Deterministic rotation","Latent-regime mixture"),
  `Benford target`=c("marginally Benford at each observation","marginally Benford at each observation","marginally Benford under random phase","pooled-Benford under fixed 50/50 weighting"),
  `Within-sequence structure`=c("independent","wrapped Gaussian random walk","irrational rotation","conditionally iid given latent regime"),
  Parameters=c(sprintf("%d sequences x %d",n_seq,seq_len),sprintf("rho = %.2f",rho),sprintf("theta = %.6f",theta),"exactly 50/50 sequences; Beta(2,1) / Beta(1,2)"),check.names=FALSE)

summarize_primary_results <- function(sim){require_output_packages();dplyr::as_tibble(sim)|>dplyr::group_by(model)|>dplyr::summarise(`Chi-square`=sprintf("%.3f (%.3f)",mean(chisq),sd(chisq)),`Reject (0.05)`=sprintf("%.3f",mean(reject_05)),`CvM W2`=sprintf("%.4f (%.4f)",mean(cvm),sd(cvm)),`B(K)`=sprintf("%.6f (%.6f)",mean(B_K),sd(B_K)),`C centered`=sprintf("%.3f (%.3f)",mean(C_centered),sd(C_centered)),.groups="drop")|>as.data.frame()}

pairwise_auc_results <- function(sim,statistics=c("chisq","cvm","B_K","C_centered"),B=1000L,seed=20260821L){models<-levels(sim$model);pairs<-combn(models,2L,simplify=FALSE);out<-list();idx<-1L;for(stat in statistics)for(pp in seq_along(pairs)){p<-pairs[[pp]];x<-sim[sim$model==p[1],stat];y<-sim[sim$model==p[2],stat];ci<-bootstrap_auc_effect(x,y,B=B,seed=seed+100L*idx);out[[idx]]<-data.frame(statistic=stat,comparison=paste(p[1],"vs",p[2]),effect=unname(ci["effect"]),lo=unname(ci["lo"]),hi=unname(ci["hi"]),stringsAsFactors=FALSE);idx<-idx+1L};do.call(rbind,out)}

representative_digit_data <- function(samples){p<-benford_first_digit_probs();do.call(rbind,lapply(samples,function(obj){d<-first_digit_from_u(as.vector(obj$u));counts<-tabulate(d,nbins=9L);data.frame(model=obj$model,digit=1:9,observed=counts/sum(counts),expected=p)}))}
plot_first_digits <- function(samples){require_output_packages();dd<-representative_digit_data(samples);ggplot2::ggplot(dd,ggplot2::aes(x=digit,y=observed))+ggplot2::geom_col(width=.75)+ggplot2::geom_point(ggplot2::aes(y=expected),size=1.6)+ggplot2::facet_wrap(~model,ncol=2)+ggplot2::scale_x_continuous(breaks=1:9)+ggplot2::labs(x="First significant digit",y="Frequency",title="Exactly the same Benford marginal, different generators",subtitle="Points show the population Benford probabilities")+ggplot2::theme_minimal(base_size=11)}
plot_chisq_distribution <- function(sim){require_output_packages();critical<-qchisq(.95,df=8);ggplot2::ggplot(sim,ggplot2::aes(x=model,y=chisq))+ggplot2::geom_boxplot(outlier.alpha=.25)+ggplot2::geom_hline(yintercept=critical,linetype="dashed")+ggplot2::coord_flip()+ggplot2::labs(x=NULL,y=expression(chi^2~"first-digit statistic"),title="Exact Benford marginals can have different finite-sample null behavior",subtitle="Dashed line: nominal 5% iid chi-square critical value")+ggplot2::theme_minimal(base_size=11)}
plot_transition_coherence <- function(sim){require_output_packages();ggplot2::ggplot(sim,ggplot2::aes(x=model,y=C_centered))+ggplot2::geom_boxplot(outlier.alpha=.25)+ggplot2::coord_flip()+ggplot2::labs(x=NULL,y="Centered circular transition coherence",title="Order information separates Benford-equivalent dynamics")+ggplot2::theme_minimal(base_size=11)}

plot_latent_mixture <- function(sample_obj){require_output_packages();stopifnot(!is.null(sample_obj$latent));u<-as.vector(t(sample_obj$u));z<-rep(sample_obj$latent,each=ncol(sample_obj$u));emp<-data.frame(u=c(u,u),group=c(ifelse(z==0,"Z = 0","Z = 1"),rep("pooled",length(u))));grid<-seq(0,1,length.out=501);th<-rbind(data.frame(u=grid,density=2*grid,group="Z = 0"),data.frame(u=grid,density=2*(1-grid),group="Z = 1"),data.frame(u=grid,density=1,group="pooled"));ggplot2::ggplot(emp,ggplot2::aes(x=u))+ggplot2::geom_histogram(ggplot2::aes(y=ggplot2::after_stat(density)),bins=50,alpha=.25)+ggplot2::geom_line(data=th,ggplot2::aes(x=u,y=density),linewidth=.8,inherit.aes=FALSE)+ggplot2::facet_wrap(~group,ncol=3)+ggplot2::labs(x=expression(U=="{"*log[10](X)*"}"),y="Density",title="Pooling can create an exactly Benford population",subtitle="Neither conditional regime is Benford; their equal-weight mixture is uniform")+ggplot2::theme_minimal(base_size=11)}

summarize_rho_sensitivity <- function(sens){require_output_packages();dplyr::as_tibble(sens)|>dplyr::group_by(rho)|>dplyr::summarise(rejection_rate=mean(reject_05),rejection_se=sqrt(rejection_rate*(1-rejection_rate)/dplyr::n()),rejection_rs1=mean(reject_rs1_05),rejection_rs1_se=sqrt(rejection_rs1*(1-rejection_rs1)/dplyr::n()),rejection_rs2=mean(reject_rs2_05),rejection_rs2_se=sqrt(rejection_rs2*(1-rejection_rs2)/dplyr::n()),rejection_wald=mean(reject_wald_05),rejection_wald_se=sqrt(rejection_wald*(1-rejection_wald)/dplyr::n()),mean_chisq=mean(chisq),mean_lambda=mean(lambda_mean),mean_rs2_df=mean(rs2_df),mean_C=mean(C_centered),se_C=sd(C_centered)/sqrt(dplyr::n()),.groups="drop")|>as.data.frame()}
plot_rho_rejection <- function(s){require_output_packages();ggplot2::ggplot(s,ggplot2::aes(x=rho,y=rejection_rate))+ggplot2::geom_hline(yintercept=.05,linetype="dashed")+ggplot2::geom_line()+ggplot2::geom_point()+ggplot2::geom_errorbar(ggplot2::aes(ymin=pmax(0,rejection_rate-1.96*rejection_se),ymax=pmin(1,rejection_rate+1.96*rejection_se)),width=.02)+ggplot2::labs(x=expression(rho),y="Rejection rate of nominal 5% iid Benford test",title="Dependence changes calibration while the population remains exactly Benford")+ggplot2::theme_minimal(base_size=11)}
plot_rho_calibration_comparison <- function(s){require_output_packages();dd<-rbind(data.frame(rho=s$rho,method="Pearson + iid reference",rate=s$rejection_rate,se=s$rejection_se),data.frame(rho=s$rho,method="second-order design correction",rate=s$rejection_rs2,se=s$rejection_rs2_se),data.frame(rho=s$rho,method="sequence-aware Wald",rate=s$rejection_wald,se=s$rejection_wald_se));ggplot2::ggplot(dd,ggplot2::aes(x=rho,y=rate,linetype=method,shape=method))+ggplot2::geom_hline(yintercept=.05,linetype="dashed")+ggplot2::geom_line()+ggplot2::geom_point()+ggplot2::geom_errorbar(ggplot2::aes(ymin=pmax(0,rate-1.96*se),ymax=pmin(1,rate+1.96*se)),width=.02)+ggplot2::labs(x=expression(rho),y="Rejection rate at nominal 5%",linetype=NULL,shape=NULL,title="Sequence-aware calibration remains stable as circular persistence increases")+ggplot2::theme_minimal(base_size=11)}
plot_rho_coherence <- function(s){require_output_packages();ggplot2::ggplot(s,ggplot2::aes(x=rho,y=mean_C))+ggplot2::geom_abline(intercept=0,slope=1,linetype="dashed")+ggplot2::geom_line()+ggplot2::geom_point()+ggplot2::geom_errorbar(ggplot2::aes(ymin=mean_C-1.96*se_C,ymax=mean_C+1.96*se_C),width=.02)+ggplot2::labs(x=expression(rho),y="Mean centered transition coherence",title="Circular transition coherence tracks the dependence parameter",subtitle="Dashed line: y = rho")+ggplot2::theme_minimal(base_size=11)}
plot_manipulation_magnitudes <- function(manip){require_output_packages();dd<-manip$data;long<-rbind(data.frame(log10_value=dd$log10_x,status="original"),data.frame(log10_value=dd$log10_x_manip,status="manipulated"));ggplot2::ggplot(long,ggplot2::aes(x=log10_value,linetype=status))+ggplot2::stat_ecdf(linewidth=.8)+ggplot2::labs(x=expression(log[10](X)),y="Empirical CDF",title="Magnitude can change while every significand remains identical")+ggplot2::theme_minimal(base_size=11)}

summarize_mixture_composition <- function(sim){require_output_packages();dplyr::as_tibble(sim)|>dplyr::group_by(design)|>dplyr::summarise(`Mean pi-hat`=mean(pi_hat),`SD pi-hat`=sd(pi_hat),`Chi-square`=sprintf("%.3f (%.3f)",mean(chisq),sd(chisq)),`Reject (0.05)`=sprintf("%.3f",mean(reject_05)),`CvM W2`=sprintf("%.4f (%.4f)",mean(cvm),sd(cvm)),`B(K)`=sprintf("%.6f (%.6f)",mean(B_K),sd(B_K)),.groups="drop")|>as.data.frame()}
plot_mixture_composition_chisq <- function(sim){require_output_packages();critical<-qchisq(.95,df=8);ggplot2::ggplot(sim,ggplot2::aes(x=design,y=chisq))+ggplot2::geom_boxplot(outlier.alpha=.25)+ggplot2::geom_hline(yintercept=critical,linetype="dashed")+ggplot2::coord_flip()+ggplot2::labs(x=NULL,y=expression(chi^2~"first-digit statistic"),title="Random cluster composition adds a separate source of Benford-test rejection",subtitle="Both designs use the same two conditional regimes; only the realized 50/50 balance differs")+ggplot2::theme_minimal(base_size=11)}
plot_mixture_composition_imbalance <- function(sim,n_total=100000L){require_output_packages();dd<-sim[as.character(sim$design)=="random Bernoulli composition",,drop=FALSE];critical<-qchisq(.95,df=8);grid<-seq(0,max(dd$imbalance)*1.04,length.out=300);theory<-data.frame(imbalance=grid,chisq=vapply(grid,function(delta)expected_chisq_latent_composition(.5+delta,n_total=n_total),numeric(1)));ggplot2::ggplot(dd,ggplot2::aes(x=imbalance,y=chisq))+ggplot2::geom_hline(yintercept=critical,linetype="dashed")+ggplot2::geom_point(alpha=.55)+ggplot2::geom_line(data=theory,ggplot2::aes(x=imbalance,y=chisq),inherit.aes=FALSE,linewidth=.8)+ggplot2::labs(x=expression(abs(hat(pi)-1/2)),y=expression(chi^2~"first-digit statistic"),title="Realized latent-regime imbalance drives the extra marginal discrepancy",subtitle="Solid curve: exact conditional E[chi-square]; dashed line: nominal 5% iid critical value")+ggplot2::theme_minimal(base_size=11)}

summarize_design_aware_calibration <- function(sim){require_output_packages();dplyr::as_tibble(sim)|>dplyr::group_by(model)|>dplyr::summarise(`Naive Pearson`=mean(reject_05,na.rm=TRUE),`RS first-order`=mean(reject_rs1_05,na.rm=TRUE),`RS second-order`=mean(reject_rs2_05,na.rm=TRUE),`Sequence Wald`=mean(reject_wald_05,na.rm=TRUE),`Mean design effect`=mean(lambda_mean,na.rm=TRUE),`Mean RS2 df`=mean(rs2_df,na.rm=TRUE),.groups="drop")|>as.data.frame()}
calibration_long_data <- function(sim){require_output_packages();dplyr::as_tibble(sim)|>dplyr::select(model,reject_05,reject_rs1_05,reject_rs2_05,reject_wald_05)|>tidyr::pivot_longer(cols=-model,names_to="method_id",values_to="reject")|>dplyr::mutate(method=dplyr::recode(method_id,reject_05="Pearson + iid reference",reject_rs1_05="first-order design correction",reject_rs2_05="second-order design correction",reject_wald_05="sequence-aware Wald"))}
plot_design_aware_rejection <- function(sim){require_output_packages();dd<-calibration_long_data(sim)|>dplyr::group_by(model,method)|>dplyr::summarise(rejection_rate=mean(reject,na.rm=TRUE),R=sum(is.finite(as.numeric(reject))),se=sqrt(rejection_rate*(1-rejection_rate)/R),.groups="drop");ggplot2::ggplot(dd,ggplot2::aes(x=method,y=rejection_rate,group=model))+ggplot2::geom_hline(yintercept=.05,linetype="dashed")+ggplot2::geom_point()+ggplot2::geom_errorbar(ggplot2::aes(ymin=pmax(0,rejection_rate-1.96*se),ymax=pmin(1,rejection_rate+1.96*se)),width=.12)+ggplot2::facet_wrap(~model,ncol=2)+ggplot2::labs(x=NULL,y="Rejection rate at nominal 5%",title="Accounting for sequence-level covariance restores calibration",subtitle="Second-order correction moment-matches the estimated weighted chi-square limit")+ggplot2::theme_minimal(base_size=11)+ggplot2::theme(axis.text.x=ggplot2::element_text(angle=25,hjust=1))}
summarize_design_spectrum <- function(sim){require_output_packages();dplyr::as_tibble(sim)|>dplyr::group_by(model)|>dplyr::summarise(`Mean lambda`=mean(lambda_mean,na.rm=TRUE),`SD mean lambda`=sd(lambda_mean,na.rm=TRUE),`Mean max lambda`=mean(lambda_max,na.rm=TRUE),`Mean RS2 scale`=mean(rs2_scale,na.rm=TRUE),`Mean RS2 df`=mean(rs2_df,na.rm=TRUE),.groups="drop")|>as.data.frame()}
summarize_mixture_composition_calibration <- function(sim){require_output_packages();dplyr::as_tibble(sim)|>dplyr::group_by(design)|>dplyr::summarise(`Mean pi-hat`=mean(pi_hat),`SD pi-hat`=sd(pi_hat),`Naive Pearson reject`=mean(reject_05,na.rm=TRUE),`RS first-order reject`=mean(reject_rs1_05,na.rm=TRUE),`RS second-order reject`=mean(reject_rs2_05,na.rm=TRUE),`Sequence Wald reject`=mean(reject_wald_05,na.rm=TRUE),`Mean design effect`=mean(lambda_mean,na.rm=TRUE),`Mean RS2 df`=mean(rs2_df,na.rm=TRUE),.groups="drop")|>as.data.frame()}
plot_mixture_composition_calibration <- function(sim){require_output_packages();dd<-dplyr::as_tibble(sim)|>dplyr::select(design,reject_05,reject_rs2_05,reject_wald_05)|>tidyr::pivot_longer(-design,names_to="method_id",values_to="reject")|>dplyr::mutate(method=dplyr::recode(method_id,reject_05="Pearson + iid reference",reject_rs2_05="second-order design correction",reject_wald_05="sequence-aware Wald"))|>dplyr::group_by(design,method)|>dplyr::summarise(rejection_rate=mean(reject,na.rm=TRUE),R=dplyr::n(),se=sqrt(rejection_rate*(1-rejection_rate)/R),.groups="drop");ggplot2::ggplot(dd,ggplot2::aes(x=method,y=rejection_rate))+ggplot2::geom_hline(yintercept=.05,linetype="dashed")+ggplot2::geom_point()+ggplot2::geom_errorbar(ggplot2::aes(ymin=pmax(0,rejection_rate-1.96*se),ymax=pmin(1,rejection_rate+1.96*se)),width=.12)+ggplot2::facet_wrap(~design,ncol=2)+ggplot2::labs(x=NULL,y="Rejection rate at nominal 5%",title="Design-aware calibration absorbs random mixture-composition variability")+ggplot2::theme_minimal(base_size=11)+ggplot2::theme(axis.text.x=ggplot2::element_text(angle=25,hjust=1))}
